//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGioiDiDong_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int maKM { get; set; }
        public string tenKM { get; set; }
        public string hinhKM { get; set; }
        public string thoihan { get; set; }
        public string chitiet { get; set; }
    }
}
